[tool.poetry]
name = "video-report"
version = "0.1.0"
description = "CLI tool for generating reports from YouTube video metrics"
authors = ["Lenar Khaidarov <haidarov_lenar@mail.ru>"]
readme = "README.md"
packages = [{include = "video_report"}]

[tool.poetry.dependencies]
python = "^3.13"
tabulate = "^0.10.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"
pytest-cov = "^7.1.0"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.3.0"
black = "^26.3.1"
isort = "^8.0.1"
mypy = "^2.1.0"
types-tabulate = "^0.10.0.20260508"
flake8-pyproject = "^1.2.4"

[tool.poetry.scripts]
coffee-report = "video_report.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v --basetemp=./tmp"
norecursedirs = [".git", "__pycache__", "*.egg-info"]

[tool.flake8]
max-line-length = 119
